server:
  port: 8080

spring:
  application:
    name: personal-knowledge-sharing-platform-backend
  datasource:
    url: jdbc:h2:file:./data/knowledge_platform;MODE=MySQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema-h2.sql
      data-locations: classpath:sql/seed-h2.sql

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

app:
  jwt:
    secret: "replace-with-at-least-32-byte-secret-key-value"
    expire-seconds: 86400
